import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './Providers'

const inter = Inter({ subsets: ['latin'] })
import { SessionProvider } from "next-auth/react"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import Header from './components/Header'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-gray-800"}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  )
}
